name: build_package_steamos

on:
  push:

      
jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-22.04
    container:
      image: ianburgwin/steamos
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
      - name: test
        run: |
          pacman -S git
          cat /etc/*-release | grep PRETTY_NAME | awk -F= '{print $2}' | tr -d '"'
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV    
             
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Building OpenHD in CHROOT
        run: |
          echo "hello world"
