name: build_package_steamos

on:
  push:

      
jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-22.04
    container:
      image: ianburgwin/steamos
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
      - name: test
        run: |
          pacman -Syu --noconfirm
          pacman -S git --noconfirm
          cat /etc/os-release | grep "^PRETTY_NAME" | cut -d= -f2- | tr -d '"' && echo -n " (" && cat /etc/os-release | grep "^VERSION_CODENAME" | cut -d= -f2- | tr -d '\n' && echo ")"
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV    
             
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Building OpenHD in Docker
        run: |
          pacman -S sudo --noconfirm
          sudo pacman -Syu --noconfirm
          flatpak remote-info --sdk flathub org.freedesktop.Sdk
          sudo pacman -S libusb libpcap libsodium libnl sdl2 libv4l git base-devel autoconf automake libtool python-pip ruby cmake gst-plugins-base boost boost-libs --noconfirm
          cd OpenHD
          sudo git config --global --add safe.directory /__w/OpenHD/OpenHD
          git config --global --add safe.directory /__w/OpenHD/OpenHD
          sudo bash build_cmake.sh